scan_timeout = 5
add_newline = false

[line_break]
disabled = true

[aws]
disabled = true

[crystal]
disabled = true

[git_status]
disabled = true

[dart]
disabled = true

[docker_context]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[dotnet]
disabled = true

[java]
disabled = true

[lua]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[php]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[swift]
disabled = true

[vagrant]
disabled = true

[terraform]
disabled = true
